// src/lib/auth/authConfig.ts

// Brevo Configuration
const brevoSenderEmail = process.env.BREVO_SENDER_EMAIL || 'info@bergmantri.com';
const brevoSenderName = process.env.BREVO_SENDER_NAME || 'Bergman Triathlon';

export const authOtpConfig = {
  brevo: {
    senderEmail: brevoSenderEmail,
    senderName: brevoSenderName,
    otpTemplateId: 178,
    registrationConfirmationTemplateId: 199,
    registrationConfirmationUSDTemplateId: 243,
    waiverOtpTemplateId: 174,
    waiverCheckedInTemplateId: 188,
    athleteCancellationTemplateId: 201,
    athleteDeferralTemplateId: 191,
    categoryChangeTemplateId: 217, // ADMIN NOTIFICATION
    categoryChangeParticipantTemplateId: 255, // ATHLETE NOTIFICATION
    adminNotificationTemplateId: 215,
    adminTicketSaleTemplateId: 254, 
    adminTicketSaleUSDTemplateId: 243,
    bikeCheckoutOtpTemplateId: 224,
    bikeCheckoutReminderTemplateId: 227,
    athleteIncompleteRegistrationTemplateId: 203,
    clubAffiliationTemplateId: 205,
    monthlyDeferralReminderTemplateId: 207,
    clubRegistrationTemplateId: 208,
    welcomeEmailTemplateId: 214,
    clubAthleteRegistrationTemplateId: 221,
    lockerAssignmentTemplateId: 223,
    lockerReturnTemplateId: 224,
    yearlyRecapTemplateId: 226,
    clubYearlyRecapTemplateId: 242,
    foodOrderTemplateId: 25,
    bikeRackingTemplateId: 234,
    athleteRemovedFromClubTemplateId: 245,
    contactEnquiryAckTemplateId: 246,
    contactEnquiryAdminTemplateId: 247,
    feedbackCouponTemplateId: 250,
    storeOrderShippedTemplateId: 251,
    storeOrderConfirmedTemplateId: 252,
    storeAdminOrderAlertTemplateId: 253,
    yearlyRecapTemplateId_new: 226, // Fallback
  },
  aisensy: {
    otpCampaignName: 'otp1',
    volunteerCheckinOtpCampaignName: 'otp1',
    regConfirmationCampaignName: 'bmregconf',
    cancellationCampaignName: 'bergmanregcan',
    categoryChangeCampaignName: 'bmlogcatchan1',
    waiverCheckedInCampaignName: 'waiverchecked1',
    bikeCheckInCampaignName: 'bikecheckin4',
    bikeCheckOutCampaignName: 'bikecheckout1',
    refundInitiatedCampaignName: 'bmcanrefund',
    adminAlertCampaignName: 'adminmessage',
    bikeCheckoutOtpCampaignName: 'bmotp',
    bikeCheckoutReminderCampaignName: 'bikecheckoutreminder',
    incompleteRegistrationCampaignName: 'potentialregistration',
    clubAffiliationCampaignName: 'clubaffliation', 
    deferralConfirmationCampaignName: 'bmdeferral1',
    clubParticipantRegCampaignName: 'clubparticipantreg',
    lockerAssignmentCampaignName: 'locker3',
    lockerReturnCampaignName: 'lockerreturn',
    foodOrderCampaignName: 'food',
    foodDeliveredCampaignName: 'fooddel',
    bikeRackingCampaignName: "bikerack",
    registrationInvoiceCampaignName: 'invoice',
    serviceFeeInvoiceCampaignName: 'Invoice def',
    feedbackCouponCampaignName: 'feedback_coupon',
    storeOrderShippedCampaignName: 'bergman_order_shipped',
    storeOrderConfirmedCampaignName: 'bergman_store_invoice',
  },
};
