// src/lib/countries.ts

export const countriesByContinent = {
  Asia: [
    { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
    { code: "BH", name: "Bahrain", flag: "🇧🇭" },
    { code: "BT", name: "Bhutan", flag: "🇧🇹" },
    { code: "BN", name: "Brunei", flag: "🇧🇳" },
    { code: "KH", name: "Cambodia", flag: "🇰🇭" },
    { code: "CN", name: "China", flag: "🇨🇳" },
    { code: "IN", name: "India", flag: "🇮🇳" },
    { code: "ID", name: "Indonesia", flag: "🇮🇩" },
    { code: "IR", name: "Iran", flag: "🇮🇷" },
    { code: "IQ", name: "Iraq", flag: "🇮🇶" },
    { code: "IL", name: "Israel", flag: "🇮🇱" },
    { code: "JP", name: "Japan", flag: "🇯🇵" },
    { code: "JO", name: "Jordan", flag: "🇯🇴" },
    { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
    { code: "KW", name: "Kuwait", flag: "🇰🇼" },
    { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
    { code: "LA", name: "Laos", flag: "🇱🇦" },
    { code: "LB", name: "Lebanon", flag: "🇱🇧" },
    { code: "MY", name: "Malaysia", flag: "🇲🇾" },
    { code: "MV", name: "Maldives", flag: "🇲🇻" },
    { code: "MN", name: "Mongolia", flag: "🇲🇳" },
    { code: "MM", name: "Myanmar", flag: "🇲🇲" },
    { code: "NP", name: "Nepal", flag: "🇳🇵" },
    { code: "OM", name: "Oman", flag: "🇴🇲" },
    { code: "PH", name: "Philippines", flag: "🇵🇭" },
    { code: "QA", name: "Qatar", flag: "🇶🇦" },
    { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "SG", name: "Singapore", flag: "🇸🇬" },
    { code: "KR", name: "South Korea", flag: "🇰🇷" },
    { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
    { code: "TH", name: "Thailand", flag: "🇹🇭" },
    { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  ],
  Europe: [
    { code: "AL", name: "Albania", flag: "🇦🇱" },
    { code: "AD", name: "Andorra", flag: "🇦🇩" },
    { code: "AT", name: "Austria", flag: "🇦🇹" },
    { code: "BY", name: "Belarus", flag: "🇧🇾" },
    { code: "BE", name: "Belgium", flag: "🇧🇪" },
    { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
    { code: "HR", name: "Croatia", flag: "🇭🇷" },
    { code: "CY", name: "Cyprus", flag: "🇨🇾" },
    { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
    { code: "DK", name: "Denmark", flag: "🇩🇰" },
    { code: "EE", name: "Estonia", flag: "🇪🇪" },
    { code: "FI", name: "Finland", flag: "🇫🇮" },
    { code: "FR", name: "France", flag: "🇫🇷" },
    { code: "GE", name: "Georgia", flag: "🇬🇪" },
    { code: "DE", name: "Germany", flag: "🇩🇪" },
    { code: "GR", name: "Greece", flag: "🇬🇷" },
    { code: "HU", name: "Hungary", flag: "🇭🇺" },
    { code: "IS", name: "Iceland", flag: "🇮🇸" },
    { code: "IE", name: "Ireland", flag: "🇮🇪" },
    { code: "IT", name: "Italy", flag: "🇮🇹" },
    { code: "LV", name: "Latvia", flag: "🇱🇻" },
    { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
    { code: "LT", name: "Lithuania", flag: "🇱🇹" },
    { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
    { code: "MT", name: "Malta", flag: "🇲🇹" },
    { code: "MD", name: "Moldova", flag: "🇲🇩" },
    { code: "MC", name: "Monaco", flag: "🇲🇨" },
    { code: "ME", name: "Montenegro", flag: "🇲🇪" },
    { code: "NL", name: "Netherlands", flag: "🇳🇱" },
    { code: "NO", name: "Norway", flag: "🇳🇴" },
    { code: "PL", name: "Poland", flag: "🇵🇱" },
    { code: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "RO", name: "Romania", flag: "🇷🇴" },
    { code: "RU", name: "Russia", flag: "🇷🇺" },
    { code: "ES", name: "Spain", flag: "🇪🇸" },
    { code: "SE", name: "Sweden", flag: "🇸🇪" },
    { code: "CH", name: "Switzerland", flag: "🇨🇭" },
    { code: "TR", name: "Turkey", flag: "🇹🇷" },
    { code: "UA", name: "Ukraine", flag: "🇺🇦" },
    { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  ],
  Americas: [
    { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬" },
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "BS", name: "Bahamas", flag: "🇧🇸" },
    { code: "BB", name: "Barbados", flag: "🇧🇧" },
    { code: "BZ", name: "Belize", flag: "🇧🇿" },
    { code: "BO", name: "Bolivia", flag: "🇧🇴" },
    { code: "BR", name: "Brazil", flag: "🇧🇷" },
    { code: "CA", name: "Canada", flag: "🇨🇦" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "CO", name: "Colombia", flag: "🇨🇴" },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
    { code: "CU", name: "Cuba", flag: "🇨🇺" },
    { code: "DM", name: "Dominica", flag: "🇩🇲" },
    { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
    { code: "EC", name: "Ecuador", flag: "🇪🇨" },
    { code: "SV", name: "El Salvador", flag: "🇸🇻" },
    { code: "GT", name: "Guatemala", flag: "🇬🇹" },
    { code: "GY", name: "Guyana", flag: "🇬🇾" },
    { code: "HT", name: "Haiti", flag: "🇭🇹" },
    { code: "HN", name: "Honduras", flag: "🇭🇳" },
    { code: "MX", name: "Mexico", flag: "🇲🇽" },
    { code: "US", name: "United States", flag: "🇺🇸" },
  ],
  Africa: [
    { code: "DZ", name: "Algeria", flag: "🇩🇿" },
    { code: "AO", name: "Angola", flag: "🇦🇴" },
    { code: "BJ", name: "Benin", flag: "🇧🇯" },
    { code: "BW", name: "Botswana", flag: "🇧🇼" },
    { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
    { code: "BI", name: "Burundi", flag: "🇧🇮" },
    { code: "CM", name: "Cameroon", flag: "🇨🇲" },
    { code: "CV", name: "Cape Verde", flag: "🇨🇻" },
    { code: "CF", name: "Central African Republic", flag: "🇨🇫" },
    { code: "TD", name: "Chad", flag: "🇹🇩" },
    { code: "KM", name: "Comoros", flag: "🇰🇲" },
    { code: "CG", name: "Congo", flag: "🇨🇬" },
    { code: "CI", name: "Côte d’Ivoire", flag: "🇨🇮" },
    { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
    { code: "EG", name: "Egypt", flag: "🇪🇬" },
    { code: "GA", name: "Gabon", flag: "🇬🇦" },
    { code: "GM", name: "Gambia", flag: "🇬🇲" },
    { code: "GH", name: "Ghana", flag: "🇬🇭" },
    { code: "GN", name: "Guinea", flag: "🇬🇳" },
    { code: "KE", name: "Kenya", flag: "🇰🇪" },
    { code: "LS", name: "Lesotho", flag: "🇱🇸" },
    { code: "LR", name: "Liberia", flag: "🇱🇷" },
    { code: "LY", name: "Libya", flag: "🇱🇾" },
    { code: "ML", name: "Mali", flag: "🇲🇱" },
    { code: "MA", name: "Morocco", flag: "🇲🇦" },
    { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
    { code: "NA", name: "Namibia", flag: "🇳🇦" },
    { code: "NG", name: "Nigeria", flag: "🇳🇬" },
    { code: "ZA", name: "South Africa", flag: "🇿🇦" },
    { code: "ZM", name: "Zambia", flag: "🇿🇲" },
    { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
  ],
  Oceania: [
    { code: "AU", name: "Australia", flag: "🇦🇺" },
    { code: "FJ", name: "Fiji", flag: "🇫🇯" },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  ],
};

/**
 * Flat, sorted country list: India first, United States second, then A→Z.
 * Use this for all public-facing country dropdowns.
 */
export const sortedCountries = (() => {
  const all = Object.values(countriesByContinent).flat();
  const pinned = ['India', 'United States'];
  const pinnedItems = pinned.map((name) => all.find((c) => c.name === name)!).filter(Boolean);
  const rest = all
    .filter((c) => !pinned.includes(c.name))
    .sort((a, b) => a.name.localeCompare(b.name));
  return [...pinnedItems, ...rest];
})();
