
// src/lib/initial-cms-data.ts
// This file contains the initial, hardcoded data for CMS-like content.
// It's used to seed the database if the content doesn't already exist.
import type { HomepageSliderItem, Page } from './types';

export const initialPages: Page[] = [
  {
    id: 'p1',
    title: 'Home',
    slug: 'home',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    blocks: [],
    url: '/',
    eventId: null,
  },
  {
    id: 'p2',
    title: 'About Us',
    slug: 'about',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: true,
    footerCategory: 'Information',
    blocks: [],
    url: '/about',
    eventId: null,
  },
  {
    id: 'p3',
    title: 'Races',
    slug: 'races',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: true,
    footerCategory: 'Races',
    blocks: [],
    url: '/races',
    eventId: null,
  },
  {
    id: 'p4',
    title: 'Results',
    slug: 'results',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: true,
    footerCategory: 'Races',
    blocks: [],
    url: '/results',
    eventId: null,
  },
  {
    id: 'p8',
    title: 'Athlete Rankings',
    slug: 'athlete-rankings',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: false,
    footerCategory: 'Explore',
    blocks: [],
    url: '/athlete-rankings',
    eventId: null,
  },
  {
    id: 'p12',
    title: 'Elite League',
    slug: 'elite-league',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: false,
    footerCategory: 'Community',
    blocks: [],
    url: '/elite-league',
    eventId: null,
  },
  {
    id: 'p11',
    title: 'Rewards',
    slug: 'rewards',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: false,
    footerCategory: 'Community',
    blocks: [],
    url: '/rewards',
    eventId: null,
  },
  {
    id: 'p10',
    title: 'Shop',
    slug: 'shop',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: true,
    footerCategory: 'Explore',
    blocks: [],
    url: '/shop',
    eventId: null,
  },
  {
    id: 'p5',
    title: 'Media',
    slug: 'media',
    published: false,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: true,
    footerCategory: 'News',
    blocks: [],
    url: '/media',
    eventId: null,
  },
  {
    id: 'p6',
    title: 'Club Rankings',
    slug: 'clubs',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: false,
    footerCategory: 'Community',
    blocks: [],
    url: '/club-rankings',
    eventId: null,
  },
  {
    id: 'p7',
    title: 'Login',
    slug: 'login',
    published: false,
    requiresLogin: false,
    showInHeader: false,
    showInFooter: false,
    footerCategory: 'Explore',
    blocks: [],
    url: '/login',
    eventId: null,
  },
  {
    id: 'p9',
    title: 'Contact Us',
    slug: 'contact-us',
    published: true,
    requiresLogin: false,
    showInHeader: true,
    showInFooter: false,
    footerCategory: 'Support',
    blocks: [],
    url: '/contact-us',
    eventId: null,
  },
  {
    id: 'p13',
    title: 'Race Photos',
    slug: 'race-photos',
    published: true,
    requiresLogin: false,
    showInHeader: false,
    showInFooter: false,
    footerCategory: 'News',
    blocks: [],
    url: '/race-photos',
    eventId: null,
  },
];

export const initialSliderItems: HomepageSliderItem[] = [
  {
    id: 'item1',
    type: 'image',
    src: 'https://bergmantri.com/wp-content/uploads/2024/05/pune-bg-1.jpg',
    alt: 'Pune Triathlon event',
    dataAiHint: 'triathlon finish line',
    eventId: null,
    customUrl: null,
    header: null,
    description: null,
    customLinkText: null,
    showOnHomepage: true,
  },
  {
    id: 'item2',
    type: 'video',
    src: 'https://assets.zyrosite.com/cdn-cgi/imagedelivery/AbGCY1s4vA--Ff3SNf0E7A/bergmantri-com/bergman-vid-YBkkQJ7dJ7iG1kE5/video.mp4',
    alt: 'Bergman event highlight video',
    eventId: null,
    customUrl: null,
    header: null,
    description: null,
    customLinkText: null,
    showOnHomepage: true,
  },
  {
    id: 'item3',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=2940&auto=format&fit=crop',
    alt: 'Athlete swimming in open water',
    dataAiHint: 'triathlon swimming',
    eventId: null,
    customUrl: null,
    header: null,
    description: null,
    customLinkText: null,
    showOnHomepage: true,
  },
  {
    id: 'item4',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1541625602330-22773444f428?q=80&w=2940&auto=format&fit=crop',
    alt: 'Cyclist on a road bike',
    dataAiHint: 'triathlon cycling',
    eventId: null,
    customUrl: null,
    header: null,
    description: null,
    customLinkText: null,
    showOnHomepage: true,
  },
];
