// src/app/api/invoice/[bookingId]/route.ts
//
// Serves the official invoice PDF for a booking. Invoices are generated by
// Zoho Books and cached in Firebase Storage at:
//   invoices_registration/Bergman_Invoice_<invoiceNumber>.pdf
//
// Lookup order:
//   1. Find the participant by bookingId (eventId hint -> direct path,
//      else collectionGroup, else per-event scan as fallback).
//   2. If the participant has an invoiceId/invoiceNumber, serve the file
//      from Firebase Storage. If it isn't there yet, fetch it from Zoho
//      via getInvoicePdf() and upload it for next time.
//   3. Otherwise return 404.
import { NextRequest, NextResponse } from 'next/server';
import { getFirestoreInstance, getStorageInstance } from '@/lib/firebaseAdmin';
import type { EventParticipant } from '@/lib/types';
import { getInvoicePdf } from '@/lib/zoho/invoice';

export const dynamic = 'force-dynamic';

async function findParticipant(bookingId: string, eventIdHint: string | null): Promise<EventParticipant | null> {
  const adminDb = getFirestoreInstance();

  // Fast path
  if (eventIdHint) {
    const directSnap = await adminDb
      .collection('events')
      .doc(eventIdHint)
      .collection('participants')
      .where('bookingId', '==', bookingId)
      .limit(1)
      .get();
    if (!directSnap.empty) return directSnap.docs[0].data() as EventParticipant;
  }

  // collectionGroup (requires single-field index)
  try {
    const cgSnap = await adminDb
      .collectionGroup('participants')
      .where('bookingId', '==', bookingId)
      .limit(1)
      .get();
    if (!cgSnap.empty) return cgSnap.docs[0].data() as EventParticipant;
  } catch (cgErr: any) {
    const code = String(cgErr?.code || '');
    const msg = String(cgErr?.message || '');
    const isMissingIndex = code === '9' || /FAILED_PRECONDITION/i.test(msg);
    if (!isMissingIndex) throw cgErr;
    console.warn(
      `[invoice] collectionGroup lookup failed (likely missing index) for bookingId=${bookingId}. Falling back to per-event scan.`
    );
  }

  // Per-event scan fallback (no index needed)
  const eventsSnap = await adminDb.collection('events').select().get();
  for (const evDoc of eventsSnap.docs) {
    const partSnap = await evDoc.ref
      .collection('participants')
      .where('bookingId', '==', bookingId)
      .limit(1)
      .get();
    if (!partSnap.empty) return partSnap.docs[0].data() as EventParticipant;
  }
  return null;
}

async function readPdfFromStorage(invoiceNumber: string, invoiceId: string): Promise<Buffer | null> {
  const bucketName = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
  if (!bucketName) return null;

  // Invoices are stored under several historical paths/naming conventions.
  // Try them all in order until we find one that exists.
  const candidates: string[] = [];
  for (const folder of ['invoices_whatsapp', 'invoices_registration', 'invoices']) {
    if (invoiceNumber) {
      candidates.push(`${folder}/Bergman_Invoice_${invoiceNumber}.pdf`);
      candidates.push(`${folder}/${invoiceNumber}.pdf`);
      candidates.push(`${folder}/Invoice_${invoiceNumber}.pdf`);
    }
    if (invoiceId) {
      candidates.push(`${folder}/${invoiceId}.pdf`);
      candidates.push(`${folder}/Bergman_Invoice_${invoiceId}.pdf`);
    }
  }

  try {
    const bucket = getStorageInstance().bucket(bucketName);
    for (const filePath of candidates) {
      try {
        const file = bucket.file(filePath);
        const [exists] = await file.exists();
        if (!exists) continue;
        const [buf] = await file.download();
        console.log(`[invoice] Served from Storage: ${filePath}`);
        return buf;
      } catch (innerErr: any) {
        console.warn(`[invoice] Storage probe failed for ${filePath}: ${innerErr?.message}`);
      }
    }
    return null;
  } catch (e: any) {
    console.warn(`[invoice] Storage read failed for invoice ${invoiceNumber || invoiceId}: ${e?.message}`);
    return null;
  }
}

export async function GET(
  request: NextRequest,
  { params }: { params: { bookingId: string } }
) {
  const { bookingId } = params;
  if (!bookingId) {
    return NextResponse.json({ success: false, message: 'Booking ID is required.' }, { status: 400 });
  }

  try {
    const eventIdHint = request.nextUrl.searchParams.get('eventId') || null;
    const participant = await findParticipant(bookingId, eventIdHint);

    if (!participant) {
      return NextResponse.json(
        { success: false, message: `No participant found with Booking ID: ${bookingId}` },
        { status: 404 }
      );
    }

    const invoiceId = String((participant as any)?.invoiceId || '').trim();
    const invoiceNumber = String((participant as any)?.invoiceNumber || '').trim();

    if (!invoiceId && !invoiceNumber) {
      return NextResponse.json(
        {
          success: false,
          message:
            'Invoice has not been generated for this booking yet. Please try again in a few minutes or contact support.',
        },
        { status: 404 }
      );
    }

    const fileLabel = invoiceNumber || invoiceId;
    const fileName = `Bergman_Invoice_${fileLabel}.pdf`;

    // 1. Try Firebase Storage cache first.
    let pdf: Buffer | null = await readPdfFromStorage(invoiceNumber, invoiceId);

    // 2. Fall back to Zoho fetch + upload to Storage for next time.
    if (!pdf && invoiceId) {
      try {
        pdf = await getInvoicePdf(invoiceId);
        if (pdf) {
          try {
            const bucketName = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
            if (bucketName) {
              const bucket = getStorageInstance().bucket(bucketName);
              const cachePath = `invoices_whatsapp/${fileName}`;
              await bucket.file(cachePath).save(new Uint8Array(pdf), {
                metadata: { contentType: 'application/pdf' },
                public: true,
              });
              console.log(`[invoice] Cached fresh PDF at ${cachePath}`);
            }
          } catch (uploadErr: any) {
            console.warn(`[invoice] Failed to cache invoice ${fileLabel} to Storage: ${uploadErr?.message}`);
          }
        }
      } catch (zohoErr: any) {
        console.error(`[invoice] Zoho fetch failed for invoice ${invoiceId}: ${zohoErr?.message}`);
      }
    }

    if (!pdf) {
      return NextResponse.json(
        {
          success: false,
          message: 'Invoice PDF is not available yet. Please try again shortly.',
        },
        { status: 503 }
      );
    }

    const inline = request.nextUrl.searchParams.get('inline') === '1';
    const disposition = `${inline ? 'inline' : 'attachment'}; filename="${fileName}"`;

    return new NextResponse(new Uint8Array(pdf), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': disposition,
        'Cache-Control': 'private, max-age=300',
      },
    });
  } catch (error: any) {
    console.error('[invoice] Failed to serve invoice PDF:', error);
    return NextResponse.json(
      { success: false, message: `Server error: ${error?.message || 'Unknown error'}` },
      { status: 500 }
    );
  }
}
